version: '3.9'
services:
  postgres:
    image: postgres
    container_name: truenorth_database
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: truenorth
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root", "-d", "truenorth", "-h", "truenorth_database"]
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - truenorthnetwork

  redis:
    container_name: truenorth_cache
    image: redis
    command: redis-server --requirepass 123456
    ports:
      - 6379:6379
    networks:
      - truenorthnetwork

networks:
  truenorthnetwork:
